=== AbhayNepal/pyx12/map/codes.xsd
<?xml version="1.0"?>
<!-- 
    $Id$
	This file is part of the pyX12 project.

    Copyright (c) 2001-2004 Kalamazoo Community Mental Health Services,
		John Holland <jholland@kazoocmh.org> <john@zoner.org>

    All rights reserved.

	Redistribution and use in source and binary forms, with or without modification, 
	are permitted provided that the following conditions are met:

	1. Redistributions of source code must retain the above copyright notice, this list 
	   of conditions and the following disclaimer. 
	
	2. Redistributions in binary form must reproduce the above copyright notice, this 
	   list of conditions and the following disclaimer in the documentation and/or other 
	   materials provided with the distribution. 
	
	3. The name of the author may not be used to endorse or promote products derived 
	   from this software without specific prior written permission. 

	THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED 
	WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
	MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO 
	EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
	EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT 
	OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
	INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
	CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
	ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF 
	THE POSSIBILITY OF SUCH DAMAGE.
-->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:element name="codesets" type="CodeSetsType"/>
 
  <xsd:complexType name="CodeSetsType">
    <xsd:sequence>
      <xsd:element name="codeset" type="CodeSetType" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="CodeSetType">
    <xsd:sequence>
      <xsd:element name="id" type="xsd:normalizedString"/>
      <xsd:element name="name" type="xsd:normalizedString"/>
      <xsd:element name="data_ele" type="xsd:normalizedString" minOccurs="0"/>
      <xsd:element name="version" type="VersionType" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="VersionType">
    <xsd:sequence>
      <xsd:element name="id" type="xsd:normalizedString"/>
      <xsd:element name="eff_dte" type="xsd:normalizedString"/>
      <xsd:element name="exp_dte" type="xsd:normalizedString"/>
      <xsd:element name="code" type="xsd:normalizedString" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

</xsd:schema>

=== AbhayNepal/pyx12/map/codes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
    $Id$
	This file is part of the pyX12 project.

    Copyright (c) 2001, 2002 Kalamazoo Community Mental Health Services,
		John Holland <jholland@kazoocmh.org> <john@zoner.org>

    All rights reserved.

	Redistribution and use in source and binary forms, with or without modification, 
	are permitted provided that the following conditions are met:

	1. Redistributions of source code must retain the above copyright notice, this list 
	   of conditions and the following disclaimer. 
	
	2. Redistributions in binary form must reproduce the above copyright notice, this 
	   list of conditions and the following disclaimer in the documentation and/or other 
	   materials provided with the distribution. 
	
	3. The name of the author may not be used to endorse or promote products derived 
	   from this software without specific prior written permission. 

	THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED 
	WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
	MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO 
	EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
	EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT 
	OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
	INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
	CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
	ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF 
	THE POSSIBILITY OF SUCH DAMAGE.
-->
<codesets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="codes.xsd" >
   <codeset>
      <id>prov_taxonomy</id>
      <name>Provider Taxonomy Code</name>
      <data_ele>127</data_ele>
      <code>101Y00000N</code>
      <code>101YA0400N</code>
      <code>101YM0800N</code>
      <code>101YP1600N</code>
      <code>101YP2500N</code>
      <code>101YS0200N</code>
      <code>106H00000N</code>
      <code>103GC0700N</code>
      <code>103S00000N</code>
      <code>103SA1800N</code>
      <code>103SA1400N</code>
      <code>103T00000N</code>
      <code>103TA0400N</code>
      <code>103TA0700N</code>
      <code>103TB0200N</code>
      <code>103TC2200N</code>
      <code>103TC0700N</code>
      <code>103TC1900N</code>
      <code>103TE1000N</code>
      <code>103TE1100N</code>
      <code>103TF0000N</code>
      <code>103TF0200N</code>
      <code>103TH0100N</code>
      <code>103TM1700N</code>
      <code>103TM1800N</code>
      <code>103TP2700N</code>
      <code>103TP2701N</code>
      <code>103TR0400N</code>
      <code>103TS0200N</code>
      <code>103TW0100N</code>
      <code>104100000N</code>
      <code>1041C0700N</code>
      <code>1041S0200N</code>
      <code>111N00000N</code>
      <code>111NI0900N</code>
      <code>111NN0400N</code>
      <code>111NN1001N</code>
      <code>111NX0100N</code>
      <code>111NX0800N</code>
      <code>111NR0200N</code>
      <code>111NS0005N</code>
      <code>111NT0100N</code>
      <code>126800000N</code>
      <code>124Q00000N</code>
      <code>126900000N</code>
      <code>122300000N</code>
      <code>1223D0001Y</code>
      <code>1223E0200Y</code>
      <code>1223X0400Y</code>
      <code>1223P0106Y</code>
      <code>1223P0221Y</code>
      <code>1223P0300Y</code>
      <code>1223P0700Y</code>
      <code>1223S0112Y</code>
      <code>1327D0700N</code>
      <code>136A00000N</code>
      <code>133V00000N</code>
      <code>133VN1006N</code>
      <code>133VN1004N</code>
      <code>133VN1005N</code>
      <code>133N00000N</code>
      <code>133NN1002N</code>
      <code>146N00000N</code>
      <code>146M00000N</code>
      <code>146L00000N</code>
      <code>152W00000N</code>
      <code>152WC0800N</code>
      <code>152WL0500N</code>
      <code>152WX0102N</code>
      <code>152WP0200N</code>
      <code>152WS0006N</code>
      <code>152WV0400N</code>
      <code>156FC0800N</code>
      <code>156FC0801N</code>
      <code>156FX1700N</code>
      <code>156FX1100N</code>
      <code>156FX1101N</code>
      <code>156FX1800N</code>
      <code>156FX1201N</code>
      <code>156FX1202N</code>
      <code>156FX1900N</code>
      <code>164W00000N</code>
      <code>164X00000N</code>
      <code>163W00000N</code>
      <code>163WA0400N</code>
      <code>163WA2000N</code>
      <code>163WC3500N</code>
      <code>163WC0400N</code>
      <code>163WC1400N</code>
      <code>163WC1500N</code>
      <code>163WC2100N</code>
      <code>163WC1600N</code>
      <code>163WC0200N</code>
      <code>163WD0400N</code>
      <code>163WD1100N</code>
      <code>163WE0003N</code>
      <code>163WE0900N</code>
      <code>163WF0300N</code>
      <code>163WG0100N</code>
      <code>163WG0000N</code>
      <code>163WG0600N</code>
      <code>163WH0500N</code>
      <code>163WH0200N</code>
      <code>163WH1000N</code>
      <code>163WI0600N</code>
      <code>163WI0500N</code>
      <code>163WL0100N</code>
      <code>163WM1400N</code>
      <code>163WM0102N</code>
      <code>163WM0705N</code>
      <code>163WN0002N</code>
      <code>163WN0003N</code>
      <code>163WN0300N</code>
      <code>163WN0800N</code>
      <code>163WN1003N</code>
      <code>163WX0002N</code>
      <code>163WX0003N</code>
      <code>163WX0106N</code>
      <code>163WX0200N</code>
      <code>163WX1000N</code>
      <code>163WX1100N</code>
      <code>163WX0800N</code>
      <code>163WX1500N</code>
      <code>163WX0601N</code>
      <code>163WP0000N</code>
      <code>163WP0218N</code>
      <code>163WP0200N</code>
      <code>163WP1700N</code>
      <code>163WP2200N</code>
      <code>163WP2201N</code>
      <code>163WP0808N</code>
      <code>163WP0809N</code>
      <code>163WP0807N</code>
      <code>163WR0400N</code>
      <code>163WR1000N</code>
      <code>163WS0200N</code>
      <code>163WS0121N</code>
      <code>163WU0100N</code>
      <code>163WW0101N</code>
      <code>163WW0000N</code>
      <code>374T00000N</code>
      <code>374U00000N</code>
      <code>376J00000N</code>
      <code>376K00000N</code>
      <code>376G00000N</code>
      <code>3747P1801N</code>
      <code>171100000N</code>
      <code>171WH0202N</code>
      <code>172A00000N</code>
      <code>176P00000N</code>
      <code>175L00000N</code>
      <code>173000000N</code>
      <code>175M00000N</code>
      <code>175F00000N</code>
      <code>1744G0900N</code>
      <code>1744P3200N</code>
      <code>1744R1103N</code>
      <code>1744R1102N</code>
      <code>174MM1900N</code>
      <code>183500000N</code>
      <code>1835G0000N</code>
      <code>1835N0905N</code>
      <code>1835N1003N</code>
      <code>1835P1200N</code>
      <code>1835P1300N</code>
      <code>1847P3400N</code>
      <code>364S00000N</code>
      <code>364SA2100N</code>
      <code>364SA2200N</code>
      <code>364SC2300N</code>
      <code>364SC1501N</code>
      <code>364SC0200N</code>
      <code>364SE0003N</code>
      <code>364SE1400N</code>
      <code>364SF0001N</code>
      <code>364SG0600N</code>
      <code>364SH1100N</code>
      <code>364SH0200N</code>
      <code>364SI0800N</code>
      <code>364SL0600N</code>
      <code>364SM0705N</code>
      <code>364SN0000N</code>
      <code>364SN0004N</code>
      <code>364SN0800N</code>
      <code>364SX0106N</code>
      <code>364SX0200N</code>
      <code>364SX0204N</code>
      <code>364SP0200N</code>
      <code>364SP1700N</code>
      <code>364SP2800N</code>
      <code>364SP0808N</code>
      <code>364SP0809N</code>
      <code>364SP0807N</code>
      <code>364SP0810N</code>
      <code>364SP0811N</code>
      <code>364SP0812N</code>
      <code>364SP0813N</code>
      <code>364SR0400N</code>
      <code>364SR1300N</code>
      <code>364SS0200N</code>
      <code>364ST0500N</code>
      <code>364SW0102N</code>
      <code>366B00000N</code>
      <code>367500000N</code>
      <code>363L00000N</code>
      <code>363LA2100N</code>
      <code>363LA2200N</code>
      <code>363LC1500N</code>
      <code>363LC0200N</code>
      <code>363LF0000N</code>
      <code>363LG0600N</code>
      <code>363LN0000N</code>
      <code>363LN0005N</code>
      <code>363LX0001N</code>
      <code>363LX0106N</code>
      <code>363LP0200N</code>
      <code>363LP0223N</code>
      <code>363LP0222N</code>
      <code>363LP1700N</code>
      <code>363LP2300N</code>
      <code>363LP0808N</code>
      <code>363LS0200N</code>
      <code>363LW0102N</code>
      <code>363A00000N</code>
      <code>363AM0700N</code>
      <code>363AS0400N</code>
      <code>203B00000N</code>
      <code>203BA0401N</code>
      <code>203BA0000Y</code>
      <code>203BA0001N</code>
      <code>203BA0002Y</code>
      <code>203BA0003Y</code>
      <code>203BA0501N</code>
      <code>203BA0502N</code>
      <code>203BA0100Y</code>
      <code>203BA0101Y</code>
      <code>203BA0503N</code>
      <code>203BA0504N</code>
      <code>203BA0200N</code>
      <code>203BA0201Y</code>
      <code>203BA0202N</code>
      <code>203BA0300Y</code>
      <code>203BB0000N</code>
      <code>203BB0001Y</code>
      <code>203BB0100Y</code>
      <code>203BC0000Y</code>
      <code>203BC0001Y</code>
      <code>203BC0100Y</code>
      <code>203BC2500Y</code>
      <code>203BC0200Y</code>
      <code>203BC0201Y</code>
      <code>203BC0202Y</code>
      <code>203BC0203Y</code>
      <code>203BC0300Y</code>
      <code>203BC0500Y</code>
      <code>203BD0100Y</code>
      <code>203BD0101Y</code>
      <code>203BD0900Y</code>
      <code>203BD0901N</code>
      <code>203BD0300N</code>
      <code>203BE0004Y</code>
      <code>203BE0100Y</code>
      <code>203BE0101Y</code>
      <code>203BE0102Y</code>
      <code>203BF0100Y</code>
      <code>203BF0201Y</code>
      <code>203BF0202N</code>
      <code>203BG0100Y</code>
      <code>203BG0000Y</code>
      <code>203BG0201Y</code>
      <code>203BG0202Y</code>
